name: Deploy

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    environment: vps

    steps:
    - uses: actions/checkout@v1
    - uses: Borales/actions-yarn@v4.2.0

    - name: Copy repository contents via scp
      uses: appleboy/scp-action@master
      env:
        HOST: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.SSHKEY }}
      with:
        source: "."
        target: "/var/www/joel.fm/src"

    - name: Executing remote command
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.SSHKEY }}
        script: |
          ls -lAh
          pwd
          cd /var/www/joel.fm/src
          yarn install
          yarn run build
          ls -lAh public
          ln -s $PWD/public /var/www/joel.fm/html-test
          ln -s /var/www/thesis.joel.fm/html /var/www/joel.fm/html-test/thesis
